version: '3.8'

services:

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: face_shield_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
